
CREATE TABLE IF NOT EXISTS MONITORING(
	TS DATETIME NOT NULL,
	URL TEXT NOT NULL,
	LABEL TEXT NOT NULL,
	RESPONSE_TIME FLOAT,
	STATUS_CODE INTEGER DEFAULT NULL,
	CONTENT_LENGTH INTEGER DEFAULT NULL

);
